### ISSUE TITLE
Disqus loads but with error

### ISSUE THREAD

**Issue by billh93** [theplatapi/react-disqus-thread#2]
Hey so I installed your package and it looks like it works but I get an error message saying `We were unable to load Disqus. If you are a moderator please see our troubleshooting guide.`

I'm pretty sure the error is coming from my end and I'm wondering if you can give me a more specific example in regarding to the props for the tags.

`<ReactDisqusComments
                        shortname="mixgif"
                        identifier="mixgif"
                        title="Example Thread"
                        url="http://localhost:3000"
                        category_id="123456"
                        onNewComment={this.handleNewComment}/>`

That's what I have and yes I have created the handleNewComment but unfortunately I can't get the comment box to load.

What am I supposed to put for the url prop? I'm working on my localhost so I put that. I also tried the url admin for the site coming from disqus end and that didn't work.

**Comment by billh93** [comment]
Hey so I finally got it to work but I had to omit certain props. Can you go more into depth with why I need `identifier, title, url and category id`? I currently only have the disqus on one static page.

I'm assuming you need to have the other props in order for your disqus comment box system to be dynamic and scalable? I'm a noobie when it comes to these things. So, if you can go to a little bit more detail that would be great! :D

**Comment by theplatapi** [comment]
Those are part of the Disqus API. Most of them are required. Please refer to their documentation for more details.
