### ISSUE TITLE
Multi-lingual websites

### ISSUE THREAD

**Issue by awwit** [theplatapi/react-disqus-thread#7]
Hi!
What about multilanguage?

Disqus supports this feature:
https://help.disqus.com/customer/portal/articles/466249-multi-lingual-websites

It would be great to see the support from you =)

**Comment by theplatapi** [comment]
Language is supported

```
/**
* `language` tells the Disqus service which language should be used.
* Please refer to https://www.transifex.com/disqus/disqus/ on which languages can be used
* If undefined, English is used as default one
*/
language: PropTypes.string
```

Just pass in the `language` prop.
