### ISSUE TITLE
[FEATURE] Add typescript typings.

### ISSUE THREAD

**Issue by wotsyula** [theplatapi/react-disqus-thread#9]
If this could be added to `package.json` under `types` field as well as a `index.d.ts` that would allow typescript users to also use this great component.

**Comment by theplatapi** [comment]
Hey, thanks for the suggestion. I'd like to help out those who use typescript, but I don't have much experience with it. I'm happy to accept a merge request with the changes.

**Comment by wotsyula** [comment]
I could do a small draft. Need to add a field to `package.json` and create a new file called `index.d.ts`. But I cannot maintain it. You will have to learn the typescript syntax (maybe a few hours) and keep it up to date yourself. Is that a deal?

I was thinking we could start with these guys implementation:

https://github.com/felixrieseberg/React-Dropzone-Component

**Comment by theplatapi** [comment]
Deal!

**Comment by wotsyula** [comment]
This should work with latest React 16 / TypeScript 2. If there are any issues due to versions I'd be happy to help out.

**Comment by mattferderer** [comment]
Looking at the TypeScript definition & the PropTypes in the actual file, what is the purpose of the id property? It doesn't seem to be used & it's required in the TypeScript definition file. 

Also shortname is marked as required in the PropTypes but optional in TypeScript via the questionmark. I'm guessing it should be required in TypeScript as well?

Lastly at the end of the file you may want to add the following to allow a default export:

```typescript
export default DisqusThread;
```

If these are changes you want, I can submit a pull request.

**Comment by theplatapi** [comment]
Good points @mattferderer. I'll merge a pull request with these changes.
